// leave off @2x/@3x
const images = {
  illustration1: require('../Images/PhoneIllustration1.png'),
  illustration2: require('../Images/PhoneIllustration2.png'),
  illustration3: require('../Images/PhoneIllustration3.png'),
  logo: require('../Images/Relate.png'),
  profile: require('../Images/Profile.png'),
  note: require('../Images/note.png'),
  house: require('../Images/House-1.png'),
  houseFocused: require('../Images/House-1-Focused.png'),
  envelope: require('../Images/Envelope-Stack.png'),
  envelopeFocused: require('../Images/Envelope-Stack-Focused.png'),
  postit: require('../Images/Post-It.png'),
  postitFocused: require('../Images/Post-It-Focused.png'),
  clock: require('../Images/Watchclock.png'),
  comments: require('../Images/Comments.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png')
}

export default images
