# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'relationship' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for relationship
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'relationshipTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'relationship-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for relationship-tvOS

  target 'relationship-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
