# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IgniteExampleLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IgniteExampleLogin
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'

  target 'IgniteExampleLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'IgniteExampleLogin-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IgniteExampleLogin-tvOS

  target 'IgniteExampleLogin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
